#!/usr/bin/python

import sys
import os
import subprocess
import re

def print_usage_and_exit():

	print 'Usage: scaleimgs <in_dir_with_images> <out_dir> <scale_factor_in_percent>'
	sys.exit(0)

if __name__ == '__main__':

	if len(sys.argv) != 4:

		print_usage_and_exit()

	in_dir_path = sys.argv[1]	
	out_dir_path = sys.argv[2]	
	factor = sys.argv[3]
	out_file_suffix = factor

	if factor[-1] != '%':

		factor += '%'

	else:

		out_file_suffix = out_file_suffix[0:-1]
	
	files_list = os.listdir(in_dir_path)
	files_list = map(lambda x: in_dir_path + os.sep + x, files_list)
	files_list = filter(lambda x: not os.path.isdir(x), files_list)
	files_list.sort()

	os.mkdir(out_dir_path)

	for file_path in files_list:

		base_name = os.path.basename(file_path)
		rgx = re.search('(.*)\.(.*)|(.*)', base_name)

		if rgx != None:

			if rgx.group(1) != None and rgx.group(2) != None:

				file_name = rgx.group(1)
				file_extension = '.' + rgx.group(2)

			else:

				file_name = rgx.group(3)
				file_extension = ''

			print file_path

			out_file_name = file_name + '_' + out_file_suffix + file_extension
			out_file_path = out_dir_path + os.sep + out_file_name
			out_file_path = os.path.normpath(out_file_path)

			subprocess.call(['convert', file_path, '-resize', factor,
					out_file_path])

			print '    ' + out_file_path
