#!/usr/bin/python

import sys
import os
import subprocess
import re

if __name__ == '__main__':

	if len(sys.argv) != 4:

		print 'Usage: scaleimgs <directory> <medium_factor> <small_factor>'

		sys.exit(0)

	files_dir_path = sys.argv[1]	
	medium_factor = sys.argv[2]
	small_factor = sys.argv[3]
	
	files_list = os.listdir(files_dir_path)
	files_list = map(lambda x: files_dir_path + os.sep + x, files_list)
	files_list.sort()

	medium_dir_path = files_dir_path + os.sep + 'medium' + os.sep
	small_dir_path = files_dir_path + os.sep + 'small' + os.sep

	medium_dir_path = os.path.normpath(medium_dir_path)
	small_dir_path = os.path.normpath(small_dir_path)

	os.mkdir(medium_dir_path)
	os.mkdir(small_dir_path)

	for file_path in files_list:

		base_name = os.path.basename(file_path)
		rgx = re.search('(.*)\.(.*)', base_name)

		if rgx != None:

			file_name = rgx.group(1)
			file_extension = rgx.group(2)

			print file_path

			medium_file_name = file_name + '_medium.' + file_extension
			small_file_name = file_name + '_small.' + file_extension
			medium_file_path = medium_dir_path + os.sep + medium_file_name 
			small_file_path = small_dir_path + os.sep + small_file_name

			medium_file_path = os.path.normpath(medium_file_path)
			small_file_path = os.path.normpath(small_file_path)

			subprocess.call(['convert', file_path, '-resize', medium_factor,
					medium_file_path])

			print '    ' + medium_file_path

			subprocess.call(['convert', file_path, '-resize', small_factor,
					small_file_path])

			print '    ' + small_file_path
